apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  # persistentVolumeReclaimPolicy: Delete
  capacity:
    storage: 5Gi # size of the storage
  accessModes: # access mode
    - ReadWriteOnce # can be mounted by a single wokrer node for reading and writing
    # - ReadOnlyMany # can be mounted by a multiple wokrer node for reading only
  hostPath:
    path: "/mnt/data"