name: Deploy K8S Manifest Files
on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v0
      id: auth
      with:
        token_format: access_token
        workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
        service_account: ${{ secrets.GCP_WORKLOAD_IDENTITY_SERVICE_ACCOUNT }}

    - name: Get Target GKE Cluster Credentials
      id: get-gke-credentials
      uses: google-github-actions/get-gke-credentials@v0
      with:
        cluster_name: ${{ secrets.GKE_CLUSTER_NAME }}
        location: ${{ secrets.GKE_CLUSTER_LOCATION }}
    
    - name: Set up Kustomize
      run: |-
        curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
        chmod u+x ./kustomize

    - name: Apply Changes
      run: |-
        sed -i.bak 's/placeholder@gserviceaccount.com/${{ secrets.GKE_SERVICE_ACCOUNT }}/' backend/service_account.yaml
        sed -i.bak 's/backend-sa/${{ secrets.GKE_BACKEND_SA }}/' backend/service_account.yaml
        sed -i.bak 's/backend-sa/${{ secrets.GKE_BACKEND_SA }}/' backend/deployment.yaml
        sed -i.bak 's/static-public-ip/${{ secrets.PUBLIC_IP_NAME }}/' base/ingress.yaml
        ./kustomize build . | kubectl apply --namespace=${{ secrets.GKE_TARGET_NAMESPACE }} -f -
