---
apiVersion: cert-manager.io/v1

kind: Certificate
metadata:
  name: base-domain-tls-certificate
  namespace: cert-manager
spec:
  secretName: base-domain-tls-certificate
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "{{ CF_base_domain }}"
  dnsNames:
  - '*.{{ CF_base_domain }}'
  - "{{ CF_base_domain }}"