---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: rancher-tls-certificate
  namespace: cert-manager
spec:
  secretName: rancher-tls-certificate
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "{{ rancher_domain }}.{{ CF_base_domain }}"
  dnsNames:
  - "{{ rancher_domain }}.{{ CF_base_domain }}"