apiVersion: v1
kind: Pod
metadata:
  name: nginx-3
  labels:
    env: stagging
  annotations:
    imageregistry: "https://hub.docker.com/"
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80