- hosts: rke2-cluster-masters[0]
#  vars:
#    helm_repos:
#      cert-manager_repo:
#         repo_name: jetstack
#         repo_url: 'https://charts.jetstack.io'

  tasks:
    - name: Include vars
      include_vars:
        dir: ../vars

#    - name: Add Helm Repos
#      kubernetes.core.helm_repository:
#        name: "{{ item.value.repo_name }}"
#        repo_url: "{{ item.value.repo_url }}"
#      loop: "{{ lookup('dict', helm_repos) }}"

    - name: Add Helm Repos
      kubernetes.core.helm_repository:
        name: jetstack
        repo_url: 'https://charts.jetstack.io'

    - name: Download CRDS.yml
      ansible.builtin.get_url:
        url: 'https://github.com/jetstack/cert-manager/releases/download/{{ cert_manager_version }}/cert-manager.crds.yaml'
        dest: ~/cert-manager.crds.yaml
        mode: '0664'

    - name: Apply CRDS.yml
      kubernetes.core.k8s:
        state: present
        src: ~/cert-manager.crds.yaml

    - name: Remove CRDS.yml
      file:
        state: absent
        path: ~/cert-manager.crds.yaml

    - name: Install Cert-Manager
      kubernetes.core.helm:
        name: cert-manager
        release_namespace: cert-manager
        chart_ref: jetstack/cert-manager

        values:
          verison: "{{ cert_manager_version }}"

        create_namespace: True
        force: False
        replace: True
        wait_timeout: 30s
        disable_hook: True
        #update_repo_cache: True
        #wait: True

    - name: Wait for Cert-Manager to be ready.
      pause:
        seconds: 30