name: Build and Push Container Image to Artifact Registry
on:
  push:
    tags:
      - 'v*.*.*'
env:
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT }}
  IMAGE_FULL_NAME: ${{ secrets.GCP_ARTIFACT_REGISTRY_LOCATION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/${{ secrets.GCP_ARTIFACT_REGISTRY_ID }}/todoapp-frontend:${{github.ref_name}}

jobs:
  setup-build-publish:
    name: Setup, Build, Publish
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v0
      id: auth
      with:
        token_format: access_token
        workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
        service_account: ${{ secrets.GCP_WORKLOAD_IDENTITY_SERVICE_ACCOUNT }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0

    - name: Authorize Atifact Registry
      run: gcloud auth configure-docker ${{ secrets.GCP_ARTIFACT_REGISTRY_LOCATION }}-docker.pkg.dev

    - name: Build Container Image
      run: |
        echo "REACT_APP_API_ENDPOINT=http://${{ secrets.PUBLIC_IP_ADDRESS }}/apis" > .env.production
        docker build -t ${{ env.IMAGE_FULL_NAME }} .

    - name: Publisher Container Image
      run: docker push ${{ env.IMAGE_FULL_NAME }}


  update-manifest:
    needs: setup-build-publish
    name: Update K8S Manifests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        repository: ${{ secrets.MANIFEST_REPOSITORY }}

    - name: Set up Kustomize
      run: |-
        curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
        chmod u+x ./kustomize

    - name: Update Image
      run: |-
        ./kustomize edit set image "todoapp-frontend=${{ env.IMAGE_FULL_NAME }}"
        rm -rf ./kustomize

    - name: Create Pull Request
      id: create-pull-request
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.PAT }}
        commit-message: "Update Frontend Image ${{github.ref_name}} | Auto-Commit"
        committer: GitHub <noreply@github.com>
        author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
        branch: update/frontend-image-${{github.ref_name}}
        delete-branch: true
        body: |
          Update Frontend Container Image
          - New Image Tag: ${{github.ref_name}}
          - Build: [Click Here][1]

          [1]: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        title: 'Update Frontend Image ${{github.ref_name}}'
        labels: |
          automated-pr
        draft: false
