- hosts: rke2-cluster
  become: true

  tasks:
    - name: Set hostnames
      hostname:
        name: "{{ inventory_hostname }}"

    - name: Swapoff
      shell: swapoff -a

    - name: Disable Swap permanently
      replace:
        path: /etc/fstab
        regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
        replace: '# \1'

    - name: Load Modules
      community.general.modprobe:
        name: "{{ item }}"
        state: present
      with_items:
       - ip_vs
       - ip_vs_rr
       - ip_vs_wrr
       - ip_vs_sh
       - nf_conntrack

    - name: Install Python-Pip and requirements
      apt:
        name:
         - python3-pip
        state: latest
        update_cache: true

    - name: Install Python dependencies
      pip:
        name: kubernetes