apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    role: backend
  annotations:
    cloud.google.com/backend-config: '{"default": "backend-http-hc-config"}'
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    role: backend
