Vagrant.configure("2") do |config|
    # This will be applied to every vagrant file that comes after it
    config.vm.box = "ubuntu/focal64"
    
    config.vm.provision "shell" do |s|
      ssh_pub_key = File.readlines("../ansible/devops.pem.pub").first.strip
      s.inline = <<-SHELL
        echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys
        echo #{ssh_pub_key} >> /root/.ssh/authorized_keys
      SHELL
    end
    # K8s Control Plane
    ## Master Node
    config.vm.define "master" do |k8s_master|
      # k8s_master.vm.provision "shell", path: "node_script.sh"
      k8s_master.vm.network "private_network", ip: "172.16.128.4" 
      k8s_master.vm.hostname = "master"
      k8s_master.vm.provider "virtualbox" do |v|
        v.customize ["modifyvm", :id, "--audio", "none"]
        v.memory = 2048
        v.cpus = 2
      end
    end
    # K8s Data Plane
    ## Worker Node 1
    config.vm.define "node1" do |k8s_worker|
      # k8s_worker.vm.provision "shell", path: "node_script.sh"
      k8s_worker.vm.network "private_network", ip: "172.16.128.5"
      k8s_worker.vm.hostname = "node1"
      k8s_worker.vm.provider "virtualbox" do |v|
        v.customize ["modifyvm", :id, "--audio", "none"]
        v.memory = 1024
        v.cpus = 2
      end
    end
    ## Worker Node 2
    config.vm.define "node2" do |k8s_worker|
      # k8s_worker.vm.provision "shell", path: "node_script.sh"
      k8s_worker.vm.network "private_network", ip: "172.16.128.6"
      k8s_worker.vm.hostname = "node2"
      k8s_worker.vm.provider "virtualbox" do |v|
        v.customize ["modifyvm", :id, "--audio", "none"]
        v.memory = 1024
        v.cpus = 2
      end
    end
  end